// dane czlonkow zespolu - czesc z formularza, reszta do uzupelnienia

window.WUT_DEPT_FILTERS = [
    { id: 'all',          label: 'Wszyscy' },
    { id: 'zarzad',       label: 'Zarząd' },
    { id: 'aero',         label: 'Aerodynamika' },
    { id: 'chassis',      label: 'Chassis' },
    { id: 'suspension',   label: 'Zawieszenie' },
    { id: 'electronics',  label: 'Elektronika' },
    { id: 'engine',       label: 'Silnik' },
    { id: 'pr',           label: 'PR' },
    { id: 'logistics',    label: 'Logistyka' },
    { id: 'fundraising',  label: 'Fundraising' },
];

window.WUT_DEPT_INFO = {
    zarzad:      { label: 'Zarząd',       defaultRole: 'Zarząd',                projectExamples: [] },
    aero:        { label: 'Aerodynamika', defaultRole: 'Inżynier aerodynamiki', projectExamples: [] },
    chassis:     { label: 'Chassis',      defaultRole: 'Inżynier nadwozia',     projectExamples: [] },
    suspension:  { label: 'Zawieszenie',  defaultRole: 'Inżynier zawieszenia',  projectExamples: [] },
    electronics: { label: 'Elektronika',  defaultRole: 'Inżynier elektroniki',  projectExamples: [] },
    engine:      { label: 'Silnik',       defaultRole: 'Inżynier silnika',      projectExamples: [] },
    pr:          { label: 'PR',           defaultRole: 'PR & Marketing',        projectExamples: [] },
    logistics:   { label: 'Logistyka',    defaultRole: 'Logistyka',             projectExamples: [] },
    fundraising: { label: 'Fundraising',  defaultRole: 'Fundraising',           projectExamples: [] },
};

// mapa wydzialow na skroty
const FAC = {
    'Mechatroniki':                                                              'PW · Mechatronika',
    'Wydział Samochodów i Maszyn Roboczych':                                     'PW · SiMR',
    'Samochodów i Maszyn Roboczych':                                             'PW · SiMR',
    'Absolwent Wydziału Samochodów i Maszyn Roboczych':                          'PW · SiMR (absolwent)',
    'Mechaniczny Technologiczny':                                                'PW · MT',
    'Wydział Mechaniczny Technologiczny':                                        'PW · MT',
    'Politechnika Warszawska, Wydział Mechaniczny Technologiczny':               'PW · MT',
    'Elektroniki i Technik Informacyjnych':                                      'PW · EiTI',
    'Wydział Elektroniki i Technik Informacyjnych':                              'PW · EiTI',
    'Elektryczny':                                                               'PW · WE',
    'Mechaniczny Energetyki i Lotnictwa':                                        'PW · MEiL',
    'Wydział Mechaniczny Energetyki i Lotnictwa':                                'PW · MEiL',
    'Wydział Mechaniczny Energetyki i Lotnictwa Politechniki Warszawskiej':      'PW · MEiL',
    'Wydział Zarządzania':                                                       'PW · WZ',
    'Wydział Inżynierii Materiałowej':                                           'PW · IM',
};

const BLANK = {
    role: 'brak',
    since: 'brak',
    studies: 'brak',
    bio: 'brak',
    achievements: [],
    projects: [],
};

window.WUT_TEAM = [

    {
        slug: 'jan-oziemski',
        name: 'Jan Oziemski',
        dept: 'aero',
        role: 'Członek',
        since: 2025,
        studies: FAC['Mechatroniki'],
        bio: 'Jako członek działu aerodynamiki zajmuję się projektowaniem i wykonaniem pakietu aerodynamicznego dla naszych najnowszych konstrukcji. Sporą część wolnego czasu spędzam na warsztacie laminując kolejne profile i przygotowując nowe foremniki.',
        achievements: [],
        projects: ['Faza wykonawcza WUT-7'],
    },
    {
        slug: 'bartlomiej-misurski',
        name: 'Bartłomiej Misiurski',
        dept: 'chassis',
        role: 'Członek',
        since: 2024,
        studies: FAC['Wydział Samochodów i Maszyn Roboczych'],
        bio: 'Zajmuję się projektowaniem i wykonaniem monocoque\'u, jego obliczeniami strukturalnymi oraz zapewnieniem zgodności konstrukcji z regulaminem Formula Student. Interesuję się materiałami kompozytowymi, szczególnie ich zastosowaniem w motorsporcie i lekkich konstrukcjach. Lubię pracę zespołową, analizę techniczną i szukanie praktycznych rozwiązań, które pozwalają połączyć wytrzymałość z niską masą konstrukcji.',
        achievements: [{ year: 2025, text: 'FS Poland 2025' }],
        projects: ['Kompozytowe wykroje foremników monocoque', 'Aluminiowe inserty', 'Wykonanie monocoque WUT-7', 'Push bar'],
    },
    {
        slug: 'damian-czerwiec',
        name: 'Damian Czerwiec',
        dept: 'suspension',
        role: 'Zawieszenie · Oklejenie bolidu',
        since: 2024,
        studies: FAC['Mechaniczny Technologiczny'],
        bio: 'Siema, jestem Damian. Na co dzień zajmuję się wieloma kwestiami związanymi z układem zawieszenia — organizacją, kontaktem z kluczowymi sponsorami, projektem własnych elementów, ale również pomagam i doradzam młodszym członkom w ich projektach. Dodatkowo wykonałem oklejenie bolidu WUT-6 oraz WUT-7. W wolnym czasie (o ile taki znajdę) jeżdżę w profesjonalnym drifcie w simracingu oraz współtworzę narzędzie treningowe dla kierowców PROXIMITER. Jestem fanem sosu 1000 Wysp.',
        achievements: [{ year: 2025, text: 'FS Austria 2025' }],
        projects: ['Układ kierowniczy WUT-7', 'Mocowania wahaczy WUT-7', 'Stanowisko spawania mocowań WUT-6/7', 'Rockery zawieszenia WUT-6', 'Inserty zawieszenia WUT-6'],
    },
    {
        slug: 'mateusz-makarewicz',
        name: 'Mateusz Makarewicz',
        dept: 'engine',
        role: 'Koordynator',
        since: 2023,
        studies: FAC['Absolwent Wydziału Samochodów i Maszyn Roboczych'],
        bio: 'Interesuję się motorsportem, zwłaszcza w kontekście nieszablonowych rozwiązań technicznych i rozwoju jednostek napędowych. Lubię motoryzację z lat 90-tych.',
        achievements: [
            { year: 2024, text: 'FS Poland 2024' },
            { year: 2025, text: 'FS Czechy 2025' },
            { year: 2025, text: 'FS Poland 2025' },
        ],
        projects: ['Układ przeniesienia napędu', 'Mocowania dyferencjału', 'Układ turbodoładowania'],
    },
    {
        slug: 'iwo-szaniawski',
        name: 'Iwo Szaniawski',
        dept: 'electronics',
        role: 'Członek',
        since: 2026,
        studies: FAC['Wydział Samochodów i Maszyn Roboczych'],
        bio: 'Jestem Iwo i w WUT Racing działam od wiosny 2026. Jako dumny członek działu elektroniki współtworzę złożone projekty systemów pokładowych w naszym bolidzie. Kocham motorsport i od najmłodszych lat rozwijałem moją pasję do technologii, również hobbistycznie w zakresie projektowania i wykonywania własnych systemów audio — łącząc pasję do precyzyjnej elektroniki z miłością do dobrego brzmienia ;)',
        achievements: [],
        projects: [],
    },
    {
        slug: 'dominik-werpachowski',
        name: 'Dominik Werpachowski',
        dept: 'suspension',
        role: 'Członek',
        since: 2024,
        studies: FAC['Elektroniki i Technik Informacyjnych'],
        bio: 'W ramach działalności w kole naukowym uczestniczę w całym procesie powstawania bolidu wyścigowego. Jednocześnie poszerzam wiedzę z zakresu dynamiki pojazdu, uczę się projektować w środowisku CAD, poznaję zasady analiz MES oraz dobierania parametrów zawieszenia. Swój rozwój inżynierski realizuję dwutorowo — wiedzę pozyskaną w kole bezpośrednio wykorzystuję we własnym projekcie, jakim jest modyfikacja i jazda torowa Mazdą MX-5 NB. Praktyczne doświadczenie mechaniczne i wnioski z zachowania własnego auta na torze pomagają mi dużo lepiej rozumieć zagadnienia oraz wyzwania pojawiające się podczas budowy naszego bolidu.',
        achievements: [],
        projects: ['Helper Spring', 'Łącznik ARB', 'Mocowanie amortyzatora'],
    },
    {
        slug: 'kasia-matejuk',
        name: 'Katarzyna Matejuk',
        dept: 'electronics',
        role: 'Członek',
        since: 2024,
        studies: FAC['Elektryczny'],
        bio: 'Tu tu du du.',
        achievements: [{ year: 2025, text: '2025 — Polska' }],
        projects: ['LVMS'],
    },
    {
        slug: 'patryk-pietrzykowski',
        name: 'Patryk Pietrzykowski',
        dept: 'aero',
        role: 'Członek',
        since: 2025,
        studies: FAC['Wydział Mechaniczny Energetyki i Lotnictwa Politechniki Warszawskiej'],
        bio: 'Interesuję się wyścigami samochodowymi F1, GT3, sim-racingiem oraz strategią wyścigową. W wolnym czasie programuję aplikacje komputerowe oraz skrypty. Uczę się mechaniki eksperymentując na swoim samochodzie. Staram się też utrzymać w dobrej formie fizycznej.',
        achievements: [],
        projects: [],
    },
    {
        slug: 'benek-jez',
        name: 'Benek Jeż',
        dept: 'aero',
        role: 'Zastępca koordynatora',
        since: 2023,
        studies: FAC['Wydział Mechaniczny Energetyki i Lotnictwa'],
        bio: 'W zespole głównie zajmuję się prowadzeniem projektu aerodynamiki i obliczeniami CFD, ale lubię też prace warsztatowe przy wytwarzaniu elementów kompozytowych. W czasie kiedy akurat nie walczę z Fluentem albo nie siedzę na warsztacie lubię grać w kosza, wspinać się, żeglować albo jeździć na nartach :))',
        achievements: [{ year: 2025, text: 'FS Austria 2025' }],
        projects: ['Sidepody i kanały chłodzenia WUT-6', 'Złożenia aero i sprinty CFD WUT-7'],
    },
    {
        slug: 'oliwier-jurczak',
        name: 'Oliwier Jurczak',
        dept: 'aero',
        role: 'Członek',
        since: 2025,
        studies: FAC['Mechaniczny Energetyki i Lotnictwa'],
        bio: 'Jestem osobą, którą od zawsze fascynowała Formuła 1 i to właśnie ona przyciągnęła mnie do świata motorsportu. Na torze kibicuję Maxowi Verstappenowi, a od strony inżynieryjnej podziwiam kunszt Adriana Neweya oraz Rossa Brawna. W zespole działam od niedawna, ale od razu postawiłem na proaktywność — między innymi przejmując stery i jako główny realizator prowadząc proces badawczy chemicznego wygładzania form z ABS-u pod elementy kompozytowe. Obecnie moje działania skupiają się na aerodynamice teoretycznej i symulacjach CFD. Swoją pasję płynnie łączę z nauką — w ramach inżynierskiej pracy przejściowej i dyplomowej dogłębnie analizuję zjawisko porpoisingu w bolidach F1 z roku 2022. Po godzinach jestem pasjonatem rozwiązywania sudoku i dla sportu potrafię z pamięci wymienić wszystkie państwa świata.',
        achievements: [],
        projects: ['Prowadzenie badań obróbki ABS', 'Wdrożenie do środowiska CFD', 'Optymalizacja modeli CAD'],
    },
    {
        slug: 'antoni-wojcik',
        name: 'Antoni Wójcik',
        dept: 'engine',
        role: 'Członek',
        since: 2025,
        studies: FAC['Samochodów i Maszyn Roboczych'],
        bio: 'Interesuję się motoryzacją, sportem i majsterkowaniem.',
        achievements: [],
        projects: ['Model stanowiska spawalniczego do wydechu', 'Tylna zębatka', 'Łapka sprzęgła i jej mocowanie'],
    },
    {
        slug: 'mateusz-drabarek',
        name: 'Mateusz Drabarek',
        dept: 'electronics',
        role: 'Kierowca · Elektronika',
        since: 2019,
        studies: FAC['Wydział Mechaniczny Technologiczny'],
        bio: 'W zespole WUT Racing zajmuję się elektroniką pojazdu, jestem kierowcą, spawam, dobrze się bawię.',
        achievements: [
            { year: 2022, text: 'FS Czechy 2022' },
            { year: 2023, text: 'FS Węgry · Niemcy · Polska 2023' },
            { year: 2024, text: 'FS Węgry · Chorwacja · Polska 2024' },
            { year: 2025, text: 'FS Austria · Polska 2025' },
        ],
        projects: ['Sprzęgło elektryczne', 'Wiązka elektryczna', 'PCB', 'Systemy bezpieczeństwa kierowcy'],
    },
    {
        slug: 'antek-starczynowski',
        name: 'Antoni Starczynowski',
        dept: 'logistics',
        role: 'Koordynator',
        since: 2024,
        studies: FAC['Wydział Zarządzania'],
        bio: 'W kole staram się zapewnić utrzymanie operacyjności oraz statusu najaktywniejszego koła naukowego PW. Prywatnie jestem piłkarskim trenerem dzieciaków w moim lokalnym klubie. Uwielbiam pichcenie czegoś smacznego w kuchni. Książki, futbol, windsurfing — ulubione formy spędzania wolnego czasu.',
        achievements: [{ year: 2025, text: 'FS Czechy 2025' }],
        projects: ['Business Plan Presentation \'26', 'Akcelerator Kół Naukowych \'25', 'Wszystkie targi'],
    },
    {
        slug: 'mikolaj-magnuski',
        name: 'Mikołaj Magnuski',
        dept: 'aero',
        role: 'Członek',
        since: 2025,
        studies: FAC['Wydział Inżynierii Materiałowej'],
        bio: 'Do moich głównych zainteresowań należą materiały kompozytowe — dlatego bardzo lubię wraz z innymi członkami koła tworzyć elementy aero z włókna węglowego. Jest to bardzo interesujący proces, który daje mi dużo satysfakcji.',
        achievements: [],
        projects: [],
    },
    {
        slug: 'szymon-rosinski',
        name: 'Szymon Rosiński',
        dept: 'aero',
        role: 'Członek',
        since: 2024,
        studies: FAC['Mechaniczny Energetyki i Lotnictwa'],
        bio: 'Studiuję Mechanikę i Projektowanie Maszyn na wydziale MEiL. Jako członek działu aerodynamiki zajmuję się projektowaniem kompozytowych elementów pakietu aerodynamicznego oraz optymalizacją ich geometrii przy pomocy narzędzi CFD. Tworzę również wizualizacje wyników tych obliczeń, a na zawodach fotografuję nasz bolid. W wolnym czasie pracuję nad własnymi projektami z zakresu mechaniki, elektroniki i druku 3D oraz realizuję się jako Jachtowy Sternik Morski.',
        achievements: [{ year: 2025, text: 'FS Poland 2025' }],
        projects: ['Druk 3D foremników aero WUT-6', 'Kanały chłodzące tarcze hamulcowe WUT-7', 'System dokumentacji i estymacji masowej kompozytów'],
    },
    {
        slug: 'kuba-czarzasty',
        name: 'Jakub Czarzasty',
        dept: 'engine',
        role: 'Zastępca koordynatora',
        since: 2024,
        studies: FAC['Wydział Samochodów i Maszyn Roboczych'],
        bio: 'Od listopada 2024 roku należę do zespołu — przez ten czas miałem szansę wykorzystać wiedzę, którą zbieram na studiach, w projektowaniu samochodów. Poza studiami lubię też jeździć na rowerze i zjeżdżać ze stoku na nartach.',
        achievements: [{ year: 2025, text: 'FS Czechy 2025' }],
        projects: ['Planowanie wydatków działu 2025/26', 'KNTI "Turbo"', 'Mocowania dyferencjału WUT-7', 'Podtrzymka spawalnicza wydechu WUT-7', 'Mocowania silnika WUT-7', 'Mocowania wydechu WUT-6'],
    },
    {
        slug: 'igor-syska',
        name: 'Igor Syska',
        dept: 'engine',
        role: 'Członek',
        since: 2023,
        studies: FAC['Wydział Mechaniczny Technologiczny'],
        bio: 'Jestem studentem trzeciego roku Mechaniki i Budowy Maszyn o specjalizacji Konstrukcja i Produkcja Broni i Amunicji. Do koła naukowego dołączyłem w 2023 roku na pierwszym roku studiów i od tamtego czasu jestem członkiem działu silnika. Poza działaniami w swoim dziale zajmuję się wieloma aspektami wykonawczymi naszego projektu, w tym technologicznością niektórych elementów i zaawansowanymi technikami, jak na przykład ulepszanie cieplne. Moje zainteresowania to między innymi: symulacje komputerowe (MES, CFD, 1D), zagadnienia z zakresu mechaniki płynów, materiałoznawstwo, techniki addytywne oraz reverse engineering.',
        achievements: [{ year: 2023, text: 'FS Austria 2023' }],
        projects: ['Układ turbodoładowania silnika', 'Symulacje silnika 1D', 'Dwukomorowy drukowany catch-tank', 'Stabilizacja kolektora dolotowego', 'Obróbka cieplna wydruków AlSi10Mg'],
    },
    {
        slug: 'jakub-krajewski',
        name: 'Jakub Krajewski',
        dept: 'aero',
        role: 'Zastępca koordynatora',
        since: 2024,
        studies: FAC['Politechnika Warszawska, Wydział Mechaniczny Technologiczny'],
        bio: 'Kompozyty & aero. Ręczna obróbka CNC: cięcie i wiele innych. Starszy Dremlowy.',
        achievements: [
            { year: 2025, text: 'FS Austria 2025' },
            { year: 2025, text: 'FS Czechy 2025' },
        ],
        projects: ['Nakładki aero na koła', 'Endplate tylnego skrzydła'],
    },
    {
        slug: 'aleksander-abramowicz',
        name: 'Aleksander Abramowicz',
        dept: 'chassis',
        role: 'Członek',
        since: 2023,
        studies: FAC['Samochodów i Maszyn Roboczych'],
        bio: 'Moja przygoda w WUT Racing kręci się wokół działu Chassis. Odpowiadam za to, aby konstrukcja nośna bolidu była lekka i wytrzymała. Przeprowadziłem wiele analiz MES, dzięki czemu kierowca naszych bolidów mógł czuć się bezpiecznie podczas dominacji na torze. Praca w tym zespole to dla mnie idealne połączenie studiów z pasją — prywatnie jestem wielkim fanem Formuły 1, można powiedzieć, że motorsportem żyję na co dzień.',
        achievements: [
            { year: 2024, text: 'FS Poland 2024' },
            { year: 2025, text: 'FS Poland 2025' },
        ],
        projects: ['Stanowisko spawania ramy WUT-7', 'Stanowisko badania sztywności skrętnej', 'Analiza MES ramy WUT-7', 'Zagłówek WUT-6', 'Analiza MES monocoque WUT-6', 'Analiza MES monocoque WUT-5', 'Owiewka kokpitu WUT-5', 'Badanie środka ciężkości WUT-4'],
    },
    {
        slug: 'nikodem-wera',
        name: 'Nikodem Wera',
        dept: 'aero',
        role: 'Członek',
        since: 2025,
        studies: FAC['Wydział Mechaniczny Energetyki i Lotnictwa'],
        bio: 'Studiuję Mechanikę i Projektowanie Maszyn. Interesuję się motoryzacją, sportami motorowymi, lotnictwem oraz astronomią.',
        achievements: [],
        projects: ['Przygotowanie WUT-6 do zawodów'],
    },
    {
        slug: 'jan-maciag',
        name: 'Jan Maciąg',
        dept: 'electronics',
        role: 'Członek',
        since: 2026,
        studies: FAC['Wydział Elektroniki i Technik Informacyjnych'],
        bio: 'Dołączyłem do działu elektroniki, żeby poszerzać wiedzę w tej dziedzinie. Bardziej interesuje mnie informatyka od strony sprzętowej i w tym kierunku chcę zdobywać doświadczenie. Realizowanie praktycznych zadań, które mają rzeczywiste zastosowanie, pozwala mi szybko się uczyć. Ponadto satysfakcję sprawia mi świadomość, że elementy, nad którymi pracuję, są faktycznie wykorzystywane.',
        achievements: [],
        projects: ['Aplikacja do telemetrii', 'PCB do obsługi LED-ów'],
    },
    {
        slug: 'tamara-saganek',
        name: 'Tamara Saganek',
        dept: 'suspension',
        role: 'Członek',
        since: 2024,
        studies: FAC['Samochodów i Maszyn Roboczych'],
        bio: 'W kole zajmuję się pracą warsztatową, projektowaniem, analizą wytrzymałościową oraz optymalizacją topologiczną elementów zawieszenia.',
        achievements: [
            { year: 2025, text: 'FS Czechy 2025' },
            { year: 2025, text: 'FS Poland 2025' },
        ],
        projects: ['Mocowania wahaczy', 'Pedał gazu', 'Przewody hamulcowe'],
    },
    {
        slug: 'kazik-michalec',
        name: 'Kazik Michalec',
        dept: 'engine',
        role: 'Członek',
        since: 2025,
        studies: FAC['Mechaniczny Energetyki i Lotnictwa'],
        bio: 'Członek działu silnika WUT Racing — zajmuje się projektowaniem i wykonaniem elementów układu paliwowego bolidu.',
        achievements: [],
        projects: ['Elementy układu paliwowego'],
    },

    // -- do uzupelnienia --

    { slug: 'aleksy-dorota',        name: 'Aleksy Dorota',        dept: 'electronics', ...BLANK },
    { slug: 'bartek-pietrzak',      name: 'Bartek Pietrzak',      dept: 'aero',        ...BLANK },
    { slug: 'bartlomiej-kolacz',    name: 'Bartłomiej Kołacz',    dept: 'chassis',     ...BLANK },
    { slug: 'blazej-molas',         name: 'Błażej Molas',         dept: 'chassis',     ...BLANK },
    { slug: 'dagmara-kucharczyk',   name: 'Dagmara Kucharczyk',   dept: 'pr',          ...BLANK },
    { slug: 'franciszek-grezbiela', name: 'Franciszek Grzebiela', dept: 'aero',        ...BLANK },
    { slug: 'franek-kajdzik',      name: 'Franek Kajdzik',        dept: 'electronics', ...BLANK },
    { slug: 'grzes-radzikowski',   name: 'Grzegorz Radzikowski',  dept: 'chassis',     ...BLANK },
    { slug: 'grzes-siedlecki',     name: 'Grzegorz Siedlecki',    dept: 'engine',      ...BLANK },
    { slug: 'grzes-spruch',        name: 'Grzegorz Spruch',       dept: 'chassis',     ...BLANK },
    { slug: 'ian-gjelleboll',      name: 'Ian Gjelleboll',        dept: 'aero',        ...BLANK },
    { slug: 'iga-gamska',          name: 'Iga Gamska',            dept: 'logistics',   ...BLANK },
    { slug: 'inka-junko',          name: 'Inka Junko',            dept: 'fundraising', ...BLANK },
    { slug: 'jakub-michalec',      name: 'Jakub Michalec',        dept: 'chassis',     ...BLANK },
    { slug: 'jan-rode',            name: 'Jan Rode',              dept: 'chassis',     ...BLANK },
    { slug: 'kacper-karpinski',    name: 'Kacper Karpiński',      dept: 'electronics', ...BLANK },
    { slug: 'kacper-kozak',        name: 'Kacper Kozak',          dept: 'suspension',  ...BLANK },
    { slug: 'kamil-grabowski',     name: 'Kamil Grabowski',       dept: 'chassis',     ...BLANK },
    { slug: 'karolina-zawadzka',   name: 'Karolina Zawadzka',     dept: 'fundraising', ...BLANK },
    { slug: 'krzysztof-gut',       name: 'Krzysztof Gut',         dept: 'zarzad',      ...BLANK, role: 'Team Captain' },
    { slug: 'kuba-kotowicz',       name: 'Kuba Kotowicz',         dept: 'electronics', ...BLANK },
    { slug: 'kuba-kraj',           name: 'Kuba Kraj',             dept: 'suspension',  ...BLANK },
    { slug: 'kuba-pacocha',        name: 'Kuba Pacocha',          dept: 'engine',      ...BLANK },
    { slug: 'lena-kaliszewska',    name: 'Lena Kaliszewska',      dept: 'pr',          ...BLANK },
    { slug: 'leon-koslarz',        name: 'Leon Koślarz',          dept: 'aero',        ...BLANK },
    { slug: 'magda-sienska',       name: 'Magda Sieńska',         dept: 'chassis',     ...BLANK },
    { slug: 'maks-wozniak',        name: 'Maks Woźniak',          dept: 'suspension',  ...BLANK },
    { slug: 'malwina-kudlak',      name: 'Malwina Kudlak',        dept: 'logistics',   ...BLANK },
    { slug: 'marcelina-hyzy',      name: 'Marcelina Hyży',        dept: 'electronics', ...BLANK },
    { slug: 'mateusz-jozwiak',     name: 'Mateusz Jóźwiak',       dept: 'engine',      ...BLANK },
    { slug: 'mateusz-krajewski',   name: 'Mateusz Krajewski',     dept: 'aero',        ...BLANK },
    { slug: 'michal-mazur',        name: 'Michał Mazur',          dept: 'electronics', ...BLANK },
    { slug: 'michal-milaniuk',     name: 'Michał Milaniuk',       dept: 'suspension',  ...BLANK },
    { slug: 'michal-morawski',     name: 'Michał Morawski',       dept: 'aero',        ...BLANK, role: 'Aerodynamics Lead' },
    { slug: 'michal-wisniewski',   name: 'Michał Wiśniewski',     dept: 'zarzad',      ...BLANK, role: 'Chief Engineer' },
    { slug: 'michal-zielinski',    name: 'Michał Zieliński',      dept: 'engine',      ...BLANK, role: 'Engine Lead' },
    { slug: 'mikolaj-cieslak',     name: 'Mikołaj Cieślak',       dept: 'chassis',     ...BLANK },
    { slug: 'mikolaj-klonowski',   name: 'Mikołaj Klonowski',     dept: 'electronics', ...BLANK, role: 'Electronics Lead' },
    { slug: 'monika-bajura',       name: 'Monika Bajura',         dept: 'fundraising', ...BLANK, role: 'Fundraising Lead' },
    { slug: 'ola-bres',            name: 'Ola Breś',              dept: 'chassis',     ...BLANK, role: 'Chassis Lead' },
    { slug: 'paulina-macek',       name: 'Paulina Macek',         dept: 'pr',          ...BLANK, role: 'PR Lead' },
    { slug: 'pawel-kruk',          name: 'Paweł Kruk',            dept: 'chassis',     ...BLANK },
    { slug: 'piotr-kilianczyk',    name: 'Piotr Kiliańczyk',      dept: 'engine',      ...BLANK },
    { slug: 'piotr-piwowarski',    name: 'Piotr Piwowarski',      dept: 'aero',        ...BLANK },
    { slug: 'robert-gruszczynski', name: 'Robert Gruszczyński',   dept: 'electronics', ...BLANK },
    { slug: 'szymon-frelik',       name: 'Szymon Frelik',         dept: 'engine',      ...BLANK },
    { slug: 'tomasz-wrobel',       name: 'Tomasz Wróbel',         dept: 'suspension',  ...BLANK },
    { slug: 'tomek-kolakowski',    name: 'Tomek Kołakowski',      dept: 'aero',        ...BLANK },
    { slug: 'wiktor-mikolajczyk',  name: 'Wiktor Mikołajczyk',    dept: 'suspension',  ...BLANK },
    { slug: 'zofia-kosmala',       name: 'Zofia Kosmala',         dept: 'aero',        ...BLANK },
    { slug: 'zofia-ladunkin',      name: 'Zofia Ładunkin',        dept: 'chassis',     ...BLANK },
];

window.WUT_getRole = function(m) {
    if (m.role) return m.role;
    return window.WUT_DEPT_INFO[m.dept] ? window.WUT_DEPT_INFO[m.dept].defaultRole : 'Członek zespołu';
};

window.WUT_getDeptLabel = function(m) {
    return window.WUT_DEPT_INFO[m.dept] ? window.WUT_DEPT_INFO[m.dept].label : '—';
};
