// sklady z poprzednich sezonow - odczytane z nazw plikow ze zdjeciami
// karty archiwalne nie maja rewersu, wiec nie ma tu opisow ani zawodow

window.WUT_TEAM_ARCHIVE = {
    '2023-24': [
        { slug: 'aleksandra-sadowska', name: 'Aleksandra Sadowska', dept: 'aero' },
        { slug: 'benedykt-jez', name: 'Benedykt Jeż', dept: 'aero' },
        { slug: 'edvin-podlevski', name: 'Edvin Podlevski', dept: 'aero', role: 'Koordynator', rank: 2 },
        { slug: 'iga-gamska', name: 'Iga Gamska', dept: 'aero' },
        { slug: 'jakub-pacocha', name: 'Jakub Pacocha', dept: 'aero' },
        { slug: 'magdalena-sienska', name: 'Magdalena Sieńska', dept: 'pr', role: 'Zastępca koordynatora', rank: 3, also: [{ dept: 'aero' }] },
        { slug: 'michal-bartoszek', name: 'Michał Bartoszek', dept: 'aero' },
        { slug: 'michal-zyto', name: 'Michał Żyto', dept: 'aero' },
        { slug: 'milosz-niedziela', name: 'Miłosz Niedziela', dept: 'aero' },
        { slug: 'rafal-szulejko', name: 'Rafał Szulejko', dept: 'aero' },
        { slug: 'tomasz-polski', name: 'Tomasz Polski', dept: 'aero', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'wiktor-gutkowski', name: 'Wiktor Gutkowski', dept: 'aero' },
        { slug: 'wojciech-baran', name: 'Wojciech Baran', dept: 'aero' },
        { slug: 'lukasz-rybakowski', name: 'Łukasz Rybakowski', dept: 'aero' },
        { slug: 'aleksander-abramowicz', name: 'Aleksander Abramowicz', dept: 'chassis' },
        { slug: 'filip-polanski', name: 'Filip Polański', dept: 'chassis' },
        { slug: 'grzegorz-spruch', name: 'Grzegorz Spruch', dept: 'chassis', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'igor-stepien', name: 'Igor Stępień', dept: 'chassis' },
        { slug: 'jan-czech', name: 'Jan Czech', dept: 'chassis' },
        { slug: 'kamil-gardyjas', name: 'Kamil Gardyjas', dept: 'chassis', role: 'Koordynator', rank: 2 },
        { slug: 'krzysztof-zarnowski', name: 'Krzysztof Żarnowski', dept: 'chassis' },
        { slug: 'igor-olczak', name: 'Igor Olczak', dept: 'fundraising' },
        { slug: 'maciej-chibowski', name: 'Maciej Chibowski', dept: 'fundraising' },
        { slug: 'maja-banasiak', name: 'Maja Banasiak', dept: 'fundraising' },
        { slug: 'mateusz-czucha', name: 'Mateusz Czucha', dept: 'fundraising' },
        { slug: 'pawel-polanowski', name: 'Paweł Polanowski', dept: 'fundraising' },
        { slug: 'zofia-wiecha', name: 'Zofia Wiecha', dept: 'fundraising', role: 'Koordynator', rank: 2 },
        { slug: 'bartosz-ciesla', name: 'Bartosz Cieśla', dept: 'electronics' },
        { slug: 'blazej-molas', name: 'Błażej Molas', dept: 'electronics' },
        { slug: 'filip-jankowski', name: 'Filip Jankowski', dept: 'electronics' },
        { slug: 'grzegorz-radzikowski', name: 'Grzegorz Radzikowski', dept: 'electronics', role: 'Koordynator', rank: 2 },
        { slug: 'jakub-marcinowski', name: 'Jakub Marcinowski', dept: 'electronics' },
        { slug: 'jan-sidor', name: 'Jan Sidor', dept: 'electronics' },
        { slug: 'kacper-kowalski', name: 'Kacper Kowalski', dept: 'electronics' },
        { slug: 'marcin-ciaston', name: 'Marcin Ciastoń', dept: 'electronics' },
        { slug: 'mateusz-drabarek', name: 'Mateusz Drabarek', dept: 'zarzad', role: 'Wiceprezes ds. technicznych', rank: 1, also: [{ dept: 'electronics' }] },
        { slug: 'michal-kramowski', name: 'Michał Kramowski', dept: 'electronics' },
        { slug: 'bartosz-lewandowski', name: 'Bartosz Lewandowski', dept: 'electronics' },
        { slug: 'patrycja-wozniak', name: 'Patrycja Woźniak', dept: 'electronics' },
        { slug: 'aleksandra-beres', name: 'Aleksandra Bereś', dept: 'logistics' },
        { slug: 'filip-langiewicz', name: 'Filip Langiewicz', dept: 'logistics' },
        { slug: 'kornelia-kolodziejska', name: 'Kornelia Kołodziejska', dept: 'zarzad', role: 'Wiceprezes ds. organizacyjnych', rank: 1, also: [{ dept: 'logistics', role: 'Koordynator · Lider działu operacyjnego', rank: 2 }, { dept: 'pr', role: 'Koordynator', rank: 2 }] },
        { slug: 'mateusz-giermek', name: 'Mateusz Giermek', dept: 'logistics', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'michal-malankiewicz', name: 'Michał Malankiewicz', dept: 'logistics' },
        { slug: 'natalia-dmytrak', name: 'Natalia Dmytrak', dept: 'logistics' },
        { slug: 'szymon-modzelewski', name: 'Szymon Modzelewski', dept: 'logistics' },
        { slug: 'adam-krawczyk', name: 'Adam Krawczyk', dept: 'pr' },
        { slug: 'kajetan-boltralik', name: 'Kajetan Bołtralik', dept: 'pr' },
        { slug: 'michal-wisniewski', name: 'Michał Wiśniewski', dept: 'pr' },
        { slug: 'franciszek-kajdzik', name: 'Franciszek Kajdzik', dept: 'engine', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'igor-syska', name: 'Igor Syska', dept: 'engine' },
        { slug: 'jakub-dzikowski', name: 'Jakub Dzikowski', dept: 'engine' },
        { slug: 'jakub-florczak', name: 'Jakub Florczak', dept: 'engine' },
        { slug: 'kamil-piszcz', name: 'Kamil Piszcz', dept: 'engine', role: 'Koordynator', rank: 2 },
        { slug: 'karol-zwolinski', name: 'Karol Zwoliński', dept: 'engine' },
        { slug: 'mateusz-makarewicz', name: 'Mateusz Makarewicz', dept: 'engine' },
        { slug: 'michal-milaniuk', name: 'Michał Milaniuk', dept: 'engine' },
        { slug: 'mikolaj-klonowski', name: 'Mikołaj Klonowski', dept: 'engine' },
        { slug: 'przemyslaw-karolak', name: 'Przemysław Karolak', dept: 'engine' },
        { slug: 'szymon-kosinski', name: 'Szymon Kosiński', dept: 'engine' },
        { slug: 'kamil-polowczyk', name: 'Kamil Polowczyk', dept: 'zarzad', role: 'Lider działu technicznego', rank: 1 },
        { slug: 'marcin-platek', name: 'Marcin Płatek', dept: 'zarzad', role: 'Prezes', rank: 0 },
        { slug: 'piotr-polakowski', name: 'Piotr Polakowski', dept: 'zarzad', role: 'Wiceprezes ds. finansowych', rank: 1 },
        { slug: 'adam-chilinski', name: 'Adam Chiliński', dept: 'suspension' },
        { slug: 'andrzej-graska', name: 'Andrzej Graska', dept: 'suspension' },
        { slug: 'grzegorz-siedlecki', name: 'Grzegorz Siedlecki', dept: 'suspension' },
        { slug: 'ian-gjelleboll', name: 'Ian Gjelleboll', dept: 'suspension', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'maciej-glen', name: 'Maciej Gleń', dept: 'suspension' },
        { slug: 'maria-sirko', name: 'Maria Sirko', dept: 'suspension' },
        { slug: 'mateusz-krajewski', name: 'Mateusz Krajewski', dept: 'suspension' },
        { slug: 'milosz-moscicki', name: 'Miłosz Mościcki', dept: 'suspension' },
        { slug: 'milosz-wnuk', name: 'Miłosz Wnuk', dept: 'suspension' },
        { slug: 'norbert-kolek', name: 'Norbert Kołek', dept: 'suspension' },
        { slug: 'szymon-drzwiecki', name: 'Szymon Drzwiecki', dept: 'suspension' },
        { slug: 'tomasz-kolakowski', name: 'Tomasz Kołakowski', dept: 'suspension', role: 'Koordynator', rank: 2 },
    ],
    '2024-25': [
        { slug: 'beniamin-buchman', name: 'Beniamin Buchman', dept: 'pr' },
        { slug: 'dagmara-legien', name: 'Dagmara Legień', dept: 'pr' },
        { slug: 'jakub-kotowicz', name: 'Jakub Kotowicz', dept: 'pr' },
        { slug: 'jakub-pacocha', name: 'Jakub Pacocha', dept: 'zarzad', role: 'Wiceprezes ds. finansowych', rank: 1, also: [{ dept: 'fundraising', role: 'Koordynator', rank: 2 }, { dept: 'pr', role: 'Zastępca koordynatora', rank: 3 }] },
        { slug: 'magdalena-sienska', name: 'Magdalena Sieńska', dept: 'zarzad', role: 'Wiceprezes ds. organizacyjnych', rank: 1, also: [{ dept: 'pr', role: 'Koordynator', rank: 2 }, { dept: 'fundraising', role: 'Zastępca koordynatora', rank: 3 }, { dept: 'aero' }] },
        { slug: 'michal-wisniewski', name: 'Michał Wiśniewski', dept: 'pr' },
        { slug: 'patrycja-wojcik', name: 'Patrycja Wójcik', dept: 'pr' },
        { slug: 'aleksandra-sadowska', name: 'Aleksandra Sadowska', dept: 'aero' },
        { slug: 'benedykt-jez', name: 'Benedykt Jeż', dept: 'aero' },
        { slug: 'iga-gamska', name: 'Iga Gamska', dept: 'aero', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'jakub-krajewski', name: 'Jakub Krajewski', dept: 'aero' },
        { slug: 'kamil-grabowski', name: 'Kamil Grabowski', dept: 'aero' },
        { slug: 'michal-zyto', name: 'Michał Żyto', dept: 'aero' },
        { slug: 'milosz-niedziela', name: 'Miłosz Niedziela', dept: 'aero' },
        { slug: 'stefan-jozefowicz-okonkwo', name: 'Stefan Józefowicz-Okonkwo', dept: 'aero' },
        { slug: 'szymon-rosinski', name: 'Szymon Rosiński', dept: 'aero' },
        { slug: 'tomasz-polski', name: 'Tomasz Polski', dept: 'aero', role: 'Koordynator', rank: 2 },
        { slug: 'wojciech-baran', name: 'Wojciech Baran', dept: 'aero' },
        { slug: 'lukasz-rybakowski', name: 'Łukasz Rybakowski', dept: 'aero' },
        { slug: 'aleksander-abramowicz', name: 'Aleksander Abramowicz', dept: 'chassis' },
        { slug: 'bartlomiej-misiurski', name: 'Bartłomiej Misiurski', dept: 'chassis' },
        { slug: 'grzegorz-spruch', name: 'Grzegorz Spruch', dept: 'chassis', role: 'Koordynator', rank: 2 },
        { slug: 'igor-stepien', name: 'Igor Stępień', dept: 'chassis' },
        { slug: 'jan-czech', name: 'Jan Czech', dept: 'chassis' },
        { slug: 'kamil-polowczyk', name: 'Kamil Polowczyk', dept: 'chassis', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'krzysztof-niebylski', name: 'Krzysztof Niebylski', dept: 'chassis' },
        { slug: 'michal-morawski', name: 'Michał Morawski', dept: 'chassis' },
        { slug: 'mikolaj-cieslak', name: 'Mikołaj Cieślak', dept: 'chassis' },
        { slug: 'bartosz-pietrzak', name: 'Bartosz Pietrzak', dept: 'electronics' },
        { slug: 'blazej-molas', name: 'Błażej Molas', dept: 'electronics', role: 'Koordynator', rank: 2 },
        { slug: 'grzegorz-radzikowski', name: 'Grzegorz Radzikowski', dept: 'zarzad', role: 'Wiceprezes ds. technicznych', rank: 1, also: [{ dept: 'electronics' }] },
        { slug: 'jakub-marcinowski', name: 'Jakub Marcinowski', dept: 'electronics' },
        { slug: 'kacper-kowalski', name: 'Kacper Kowalski', dept: 'electronics', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'karolina-ratajczyk', name: 'Karolina Ratajczyk', dept: 'electronics' },
        { slug: 'katarzyna-matejuk', name: 'Katarzyna Matejuk', dept: 'electronics' },
        { slug: 'mateusz-drabarek', name: 'Mateusz Drabarek', dept: 'electronics' },
        { slug: 'milosz-moscicki', name: 'Miłosz Mościcki', dept: 'electronics' },
        { slug: 'patrycja-wozniak', name: 'Patrycja Woźniak', dept: 'electronics' },
        { slug: 'karolina-zawadzka', name: 'Karolina Zawadzka', dept: 'fundraising' },
        { slug: 'lukasz-cwalina', name: 'Łukasz Cwalina', dept: 'fundraising' },
        { slug: 'aleksandra-beres', name: 'Aleksandra Bereś', dept: 'logistics' },
        { slug: 'antoni-starczynowski', name: 'Antoni Starczynowski', dept: 'logistics' },
        { slug: 'maciej-stradowski', name: 'Maciej Stradowski', dept: 'logistics' },
        { slug: 'szymon-modzelewski', name: 'Szymon Modzelewski', dept: 'logistics', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'mateusz-giermek', name: 'Mateusz Giermek', dept: 'logistics', role: 'Koordynator', rank: 2 },
        { slug: 'franciszek-kajdzik', name: 'Franciszek Kajdzik', dept: 'engine' },
        { slug: 'igor-syska', name: 'Igor Syska', dept: 'engine' },
        { slug: 'jakub-czarzasty', name: 'Jakub Czarzasty', dept: 'engine' },
        { slug: 'jakub-dzikowski', name: 'Jakub Dzikowski', dept: 'engine' },
        { slug: 'jakub-florczak', name: 'Jakub Florczak', dept: 'engine' },
        { slug: 'kacper-karpinski', name: 'Kacper Karpiński', dept: 'engine' },
        { slug: 'kamil-piszcz', name: 'Kamil Piszcz', dept: 'engine', role: 'Zastępca koordynatora', rank: 3 },
        { slug: 'marcel-szpanel', name: 'Marcel Szpanel', dept: 'engine' },
        { slug: 'mateusz-makarewicz', name: 'Mateusz Makarewicz', dept: 'engine' },
        { slug: 'michal-milaniuk', name: 'Michał Milaniuk', dept: 'engine', role: 'Koordynator', rank: 2 },
        { slug: 'michal-mazur', name: 'Michał Mazur', dept: 'engine' },
        { slug: 'mikolaj-klonowski', name: 'Mikołaj Klonowski', dept: 'engine' },
        { slug: 'wiktor-leyko', name: 'Wiktor Leyko', dept: 'engine' },
        { slug: 'marcin-platek', name: 'Marcin Płatek', dept: 'zarzad', role: 'Prezes', rank: 0 },
        { slug: 'andrzej-graska', name: 'Andrzej Graska', dept: 'suspension' },
        { slug: 'damian-czerwiec', name: 'Damian Czerwiec', dept: 'suspension' },
        { slug: 'dominik-werpachowski', name: 'Dominik Werpachowski', dept: 'suspension' },
        { slug: 'ian-gjelleboll', name: 'Ian Gjelleboll', dept: 'suspension' },
        { slug: 'maksymilian-wozniak', name: 'Maksymilian Woźniak', dept: 'suspension' },
        { slug: 'mateusz-krajewski', name: 'Mateusz Krajewski', dept: 'suspension' },
        { slug: 'mieczyslaw-pankiewicz', name: 'Mieczysław Pankiewicz', dept: 'suspension' },
        { slug: 'tamara-saganek', name: 'Tamara Saganek', dept: 'suspension' },
        { slug: 'tomasz-kolakowski', name: 'Tomasz Kołakowski', dept: 'suspension', role: 'Koordynator', rank: 2 },
        { slug: 'grzegorz-siedlecki', name: 'Grzegorz Siedlecki', dept: 'suspension' },
        { slug: 'maria-sirko', name: 'Maria Sirko', dept: 'suspension' },
    ],
};
